/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author user
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();
        jButton21 = new javax.swing.JButton();
        jButton22 = new javax.swing.JButton();
        jButton23 = new javax.swing.JButton();
        jButton24 = new javax.swing.JButton();
        jButton25 = new javax.swing.JButton();
        jButton26 = new javax.swing.JButton();
        jButton27 = new javax.swing.JButton();
        jButton28 = new javax.swing.JButton();
        jButton29 = new javax.swing.JButton();
        jButton30 = new javax.swing.JButton();
        jButton31 = new javax.swing.JButton();
        jButton32 = new javax.swing.JButton();
        jButton33 = new javax.swing.JButton();
        jButton34 = new javax.swing.JButton();
        jButton35 = new javax.swing.JButton();
        jButton36 = new javax.swing.JButton();
        jButton37 = new javax.swing.JButton();
        jButton38 = new javax.swing.JButton();
        jButton39 = new javax.swing.JButton();
        jButton40 = new javax.swing.JButton();
        jButton41 = new javax.swing.JButton();
        jButton42 = new javax.swing.JButton();
        jButton43 = new javax.swing.JButton();
        jButton44 = new javax.swing.JButton();
        jButton45 = new javax.swing.JButton();
        jButton46 = new javax.swing.JButton();
        jButton47 = new javax.swing.JButton();
        jButton48 = new javax.swing.JButton();
        jButton49 = new javax.swing.JButton();
        jButton50 = new javax.swing.JButton();
        jButton51 = new javax.swing.JButton();
        jButton52 = new javax.swing.JButton();
        jButton53 = new javax.swing.JButton();
        jButton54 = new javax.swing.JButton();
        jButton55 = new javax.swing.JButton();
        jButton56 = new javax.swing.JButton();
        jButton57 = new javax.swing.JButton();
        jButton58 = new javax.swing.JButton();
        jButton59 = new javax.swing.JButton();
        jButton60 = new javax.swing.JButton();
        jButton61 = new javax.swing.JButton();
        jButton62 = new javax.swing.JButton();
        jButton63 = new javax.swing.JButton();
        jButton64 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextField1.setText("jTextField1");

        jTextField2.setText("jTextField2");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 212, Short.MAX_VALUE)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextField2, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                    .addComponent(jTextField1))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        jPanel3.setLayout(new java.awt.GridLayout(8, 8, 8, 8));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/black.gif"))); // NOI18N
        jButton1.setText("00");
        jButton1.setMaximumSize(new java.awt.Dimension(50, 50));
        jButton1.setMinimumSize(new java.awt.Dimension(50, 50));
        jButton1.setPreferredSize(new java.awt.Dimension(50, 50));
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1);

        jButton2.setText("jButton1");
        jButton2.setMaximumSize(new java.awt.Dimension(50, 50));
        jButton2.setMinimumSize(new java.awt.Dimension(50, 50));
        jButton2.setPreferredSize(new java.awt.Dimension(50, 50));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton2);

        jButton3.setText("jButton1");
        jButton3.setMaximumSize(new java.awt.Dimension(50, 50));
        jButton3.setMinimumSize(new java.awt.Dimension(50, 50));
        jButton3.setPreferredSize(new java.awt.Dimension(50, 50));
        jPanel3.add(jButton3);

        jButton4.setText("jButton1");
        jButton4.setMaximumSize(new java.awt.Dimension(50, 50));
        jButton4.setMinimumSize(new java.awt.Dimension(50, 50));
        jButton4.setPreferredSize(new java.awt.Dimension(50, 50));
        jPanel3.add(jButton4);

        jButton5.setText("jButton1");
        jButton5.setMaximumSize(new java.awt.Dimension(50, 50));
        jButton5.setMinimumSize(new java.awt.Dimension(50, 50));
        jButton5.setPreferredSize(new java.awt.Dimension(50, 50));
        jPanel3.add(jButton5);

        jButton6.setText("jButton1");
        jButton6.setMaximumSize(new java.awt.Dimension(50, 50));
        jButton6.setMinimumSize(new java.awt.Dimension(50, 50));
        jButton6.setPreferredSize(new java.awt.Dimension(50, 50));
        jPanel3.add(jButton6);

        jButton7.setText("jButton1");
        jButton7.setMaximumSize(new java.awt.Dimension(50, 50));
        jButton7.setMinimumSize(new java.awt.Dimension(50, 50));
        jButton7.setPreferredSize(new java.awt.Dimension(50, 50));
        jPanel3.add(jButton7);

        jButton8.setText("jButton1");
        jButton8.setMaximumSize(new java.awt.Dimension(50, 50));
        jButton8.setMinimumSize(new java.awt.Dimension(50, 50));
        jButton8.setPreferredSize(new java.awt.Dimension(50, 50));
        jPanel3.add(jButton8);

        jButton9.setText("jButton1");
        jButton9.setMaximumSize(new java.awt.Dimension(50, 50));
        jButton9.setMinimumSize(new java.awt.Dimension(50, 50));
        jButton9.setPreferredSize(new java.awt.Dimension(50, 50));
        jPanel3.add(jButton9);

        jButton10.setText("jButton1");
        jButton10.setMaximumSize(new java.awt.Dimension(50, 50));
        jButton10.setMinimumSize(new java.awt.Dimension(50, 50));
        jButton10.setPreferredSize(new java.awt.Dimension(50, 50));
        jPanel3.add(jButton10);

        jButton11.setText("jButton1");
        jButton11.setMaximumSize(new java.awt.Dimension(50, 50));
        jButton11.setMinimumSize(new java.awt.Dimension(50, 50));
        jButton11.setPreferredSize(new java.awt.Dimension(50, 50));
        jPanel3.add(jButton11);

        jButton12.setText("jButton1");
        jButton12.setMaximumSize(new java.awt.Dimension(50, 50));
        jButton12.setMinimumSize(new java.awt.Dimension(50, 50));
        jButton12.setPreferredSize(new java.awt.Dimension(50, 50));
        jPanel3.add(jButton12);

        jButton13.setText("jButton1");
        jButton13.setMaximumSize(new java.awt.Dimension(50, 50));
        jButton13.setMinimumSize(new java.awt.Dimension(50, 50));
        jButton13.setPreferredSize(new java.awt.Dimension(50, 50));
        jPanel3.add(jButton13);

        jButton14.setText("jButton1");
        jButton14.setMaximumSize(new java.awt.Dimension(50, 50));
        jButton14.setMinimumSize(new java.awt.Dimension(50, 50));
        jButton14.setPreferredSize(new java.awt.Dimension(50, 50));
        jPanel3.add(jButton14);

        jButton15.setText("jButton1");
        jButton15.setMaximumSize(new java.awt.Dimension(50, 50));
        jButton15.setMinimumSize(new java.awt.Dimension(50, 50));
        jButton15.setPreferredSize(new java.awt.Dimension(50, 50));
        jPanel3.add(jButton15);

        jButton16.setText("jButton1");
        jButton16.setMaximumSize(new java.awt.Dimension(50, 50));
        jButton16.setMinimumSize(new java.awt.Dimension(50, 50));
        jButton16.setPreferredSize(new java.awt.Dimension(50, 50));
        jPanel3.add(jButton16);

        jButton17.setText("jButton1");
        jButton17.setMaximumSize(new java.awt.Dimension(50, 50));
        jButton17.setMinimumSize(new java.awt.Dimension(50, 50));
        jButton17.setPreferredSize(new java.awt.Dimension(50, 50));
        jPanel3.add(jButton17);

        jButton18.setText("jButton1");
        jButton18.setMaximumSize(new java.awt.Dimension(50, 50));
        jButton18.setMinimumSize(new java.awt.Dimension(50, 50));
        jButton18.setPreferredSize(new java.awt.Dimension(50, 50));
        jPanel3.add(jButton18);

        jButton19.setText("jButton1");
        jButton19.setMaximumSize(new java.awt.Dimension(50, 50));
        jButton19.setMinimumSize(new java.awt.Dimension(50, 50));
        jButton19.setPreferredSize(new java.awt.Dimension(50, 50));
        jPanel3.add(jButton19);

        jButton20.setText("jButton1");
        jButton20.setMaximumSize(new java.awt.Dimension(50, 50));
        jButton20.setMinimumSize(new java.awt.Dimension(50, 50));
        jButton20.setPreferredSize(new java.awt.Dimension(50, 50));
        jPanel3.add(jButton20);

        jButton21.setText("jButton1");
        jButton21.setMaximumSize(new java.awt.Dimension(50, 50));
        jButton21.setMinimumSize(new java.awt.Dimension(50, 50));
        jButton21.setPreferredSize(new java.awt.Dimension(50, 50));
        jPanel3.add(jButton21);

        jButton22.setText("jButton1");
        jButton22.setMaximumSize(new java.awt.Dimension(50, 50));
        jButton22.setMinimumSize(new java.awt.Dimension(50, 50));
        jButton22.setPreferredSize(new java.awt.Dimension(50, 50));
        jPanel3.add(jButton22);

        jButton23.setText("jButton1");
        jButton23.setMaximumSize(new java.awt.Dimension(50, 50));
        jButton23.setMinimumSize(new java.awt.Dimension(50, 50));
        jButton23.setPreferredSize(new java.awt.Dimension(50, 50));
        jPanel3.add(jButton23);

        jButton24.setText("jButton1");
        jButton24.setMaximumSize(new java.awt.Dimension(50, 50));
        jButton24.setMinimumSize(new java.awt.Dimension(50, 50));
        jButton24.setPreferredSize(new java.awt.Dimension(50, 50));
        jPanel3.add(jButton24);

        jButton25.setText("jButton1");
        jButton25.setMaximumSize(new java.awt.Dimension(50, 50));
        jButton25.setMinimumSize(new java.awt.Dimension(50, 50));
        jButton25.setPreferredSize(new java.awt.Dimension(50, 50));
        jPanel3.add(jButton25);

        jButton26.setText("jButton1");
        jButton26.setMaximumSize(new java.awt.Dimension(50, 50));
        jButton26.setMinimumSize(new java.awt.Dimension(50, 50));
        jButton26.setPreferredSize(new java.awt.Dimension(50, 50));
        jPanel3.add(jButton26);

        jButton27.setText("jButton1");
        jButton27.setMaximumSize(new java.awt.Dimension(50, 50));
        jButton27.setMinimumSize(new java.awt.Dimension(50, 50));
        jButton27.setPreferredSize(new java.awt.Dimension(50, 50));
        jPanel3.add(jButton27);

        jButton28.setText("jButton1");
        jButton28.setMaximumSize(new java.awt.Dimension(50, 50));
        jButton28.setMinimumSize(new java.awt.Dimension(50, 50));
        jButton28.setPreferredSize(new java.awt.Dimension(50, 50));
        jPanel3.add(jButton28);

        jButton29.setText("jButton1");
        jButton29.setMaximumSize(new java.awt.Dimension(50, 50));
        jButton29.setMinimumSize(new java.awt.Dimension(50, 50));
        jButton29.setPreferredSize(new java.awt.Dimension(50, 50));
        jPanel3.add(jButton29);

        jButton30.setText("jButton1");
        jButton30.setMaximumSize(new java.awt.Dimension(50, 50));
        jButton30.setMinimumSize(new java.awt.Dimension(50, 50));
        jButton30.setPreferredSize(new java.awt.Dimension(50, 50));
        jPanel3.add(jButton30);

        jButton31.setText("jButton1");
        jButton31.setMaximumSize(new java.awt.Dimension(50, 50));
        jButton31.setMinimumSize(new java.awt.Dimension(50, 50));
        jButton31.setPreferredSize(new java.awt.Dimension(50, 50));
        jPanel3.add(jButton31);

        jButton32.setText("jButton1");
        jButton32.setMaximumSize(new java.awt.Dimension(50, 50));
        jButton32.setMinimumSize(new java.awt.Dimension(50, 50));
        jButton32.setPreferredSize(new java.awt.Dimension(50, 50));
        jPanel3.add(jButton32);

        jButton33.setText("jButton1");
        jButton33.setMaximumSize(new java.awt.Dimension(50, 50));
        jButton33.setMinimumSize(new java.awt.Dimension(50, 50));
        jButton33.setPreferredSize(new java.awt.Dimension(50, 50));
        jPanel3.add(jButton33);

        jButton34.setText("jButton1");
        jButton34.setMaximumSize(new java.awt.Dimension(50, 50));
        jButton34.setMinimumSize(new java.awt.Dimension(50, 50));
        jButton34.setPreferredSize(new java.awt.Dimension(50, 50));
        jPanel3.add(jButton34);

        jButton35.setText("jButton1");
        jButton35.setMaximumSize(new java.awt.Dimension(50, 50));
        jButton35.setMinimumSize(new java.awt.Dimension(50, 50));
        jButton35.setPreferredSize(new java.awt.Dimension(50, 50));
        jPanel3.add(jButton35);

        jButton36.setText("jButton1");
        jButton36.setMaximumSize(new java.awt.Dimension(50, 50));
        jButton36.setMinimumSize(new java.awt.Dimension(50, 50));
        jButton36.setPreferredSize(new java.awt.Dimension(50, 50));
        jPanel3.add(jButton36);

        jButton37.setText("jButton1");
        jButton37.setMaximumSize(new java.awt.Dimension(50, 50));
        jButton37.setMinimumSize(new java.awt.Dimension(50, 50));
        jButton37.setPreferredSize(new java.awt.Dimension(50, 50));
        jPanel3.add(jButton37);

        jButton38.setText("jButton1");
        jButton38.setMaximumSize(new java.awt.Dimension(50, 50));
        jButton38.setMinimumSize(new java.awt.Dimension(50, 50));
        jButton38.setPreferredSize(new java.awt.Dimension(50, 50));
        jPanel3.add(jButton38);

        jButton39.setText("jButton1");
        jButton39.setMaximumSize(new java.awt.Dimension(50, 50));
        jButton39.setMinimumSize(new java.awt.Dimension(50, 50));
        jButton39.setPreferredSize(new java.awt.Dimension(50, 50));
        jPanel3.add(jButton39);

        jButton40.setText("jButton1");
        jButton40.setMaximumSize(new java.awt.Dimension(50, 50));
        jButton40.setMinimumSize(new java.awt.Dimension(50, 50));
        jButton40.setPreferredSize(new java.awt.Dimension(50, 50));
        jPanel3.add(jButton40);

        jButton41.setText("jButton1");
        jButton41.setMaximumSize(new java.awt.Dimension(50, 50));
        jButton41.setMinimumSize(new java.awt.Dimension(50, 50));
        jButton41.setPreferredSize(new java.awt.Dimension(50, 50));
        jPanel3.add(jButton41);

        jButton42.setText("jButton1");
        jButton42.setMaximumSize(new java.awt.Dimension(50, 50));
        jButton42.setMinimumSize(new java.awt.Dimension(50, 50));
        jButton42.setPreferredSize(new java.awt.Dimension(50, 50));
        jPanel3.add(jButton42);

        jButton43.setText("jButton1");
        jButton43.setMaximumSize(new java.awt.Dimension(50, 50));
        jButton43.setMinimumSize(new java.awt.Dimension(50, 50));
        jButton43.setPreferredSize(new java.awt.Dimension(50, 50));
        jPanel3.add(jButton43);

        jButton44.setText("jButton1");
        jButton44.setMaximumSize(new java.awt.Dimension(50, 50));
        jButton44.setMinimumSize(new java.awt.Dimension(50, 50));
        jButton44.setPreferredSize(new java.awt.Dimension(50, 50));
        jPanel3.add(jButton44);

        jButton45.setText("jButton1");
        jButton45.setMaximumSize(new java.awt.Dimension(50, 50));
        jButton45.setMinimumSize(new java.awt.Dimension(50, 50));
        jButton45.setPreferredSize(new java.awt.Dimension(50, 50));
        jPanel3.add(jButton45);

        jButton46.setText("jButton1");
        jButton46.setMaximumSize(new java.awt.Dimension(50, 50));
        jButton46.setMinimumSize(new java.awt.Dimension(50, 50));
        jButton46.setPreferredSize(new java.awt.Dimension(50, 50));
        jPanel3.add(jButton46);

        jButton47.setText("jButton1");
        jButton47.setMaximumSize(new java.awt.Dimension(50, 50));
        jButton47.setMinimumSize(new java.awt.Dimension(50, 50));
        jButton47.setPreferredSize(new java.awt.Dimension(50, 50));
        jPanel3.add(jButton47);

        jButton48.setText("jButton1");
        jButton48.setMaximumSize(new java.awt.Dimension(50, 50));
        jButton48.setMinimumSize(new java.awt.Dimension(50, 50));
        jButton48.setPreferredSize(new java.awt.Dimension(50, 50));
        jPanel3.add(jButton48);

        jButton49.setText("jButton1");
        jButton49.setMaximumSize(new java.awt.Dimension(50, 50));
        jButton49.setMinimumSize(new java.awt.Dimension(50, 50));
        jButton49.setPreferredSize(new java.awt.Dimension(50, 50));
        jPanel3.add(jButton49);

        jButton50.setText("jButton1");
        jButton50.setMaximumSize(new java.awt.Dimension(50, 50));
        jButton50.setMinimumSize(new java.awt.Dimension(50, 50));
        jButton50.setPreferredSize(new java.awt.Dimension(50, 50));
        jPanel3.add(jButton50);

        jButton51.setText("jButton1");
        jButton51.setMaximumSize(new java.awt.Dimension(50, 50));
        jButton51.setMinimumSize(new java.awt.Dimension(50, 50));
        jButton51.setPreferredSize(new java.awt.Dimension(50, 50));
        jPanel3.add(jButton51);

        jButton52.setText("jButton1");
        jButton52.setMaximumSize(new java.awt.Dimension(50, 50));
        jButton52.setMinimumSize(new java.awt.Dimension(50, 50));
        jButton52.setPreferredSize(new java.awt.Dimension(50, 50));
        jPanel3.add(jButton52);

        jButton53.setText("jButton1");
        jButton53.setMaximumSize(new java.awt.Dimension(50, 50));
        jButton53.setMinimumSize(new java.awt.Dimension(50, 50));
        jButton53.setPreferredSize(new java.awt.Dimension(50, 50));
        jPanel3.add(jButton53);

        jButton54.setText("jButton1");
        jButton54.setMaximumSize(new java.awt.Dimension(50, 50));
        jButton54.setMinimumSize(new java.awt.Dimension(50, 50));
        jButton54.setPreferredSize(new java.awt.Dimension(50, 50));
        jPanel3.add(jButton54);

        jButton55.setText("jButton1");
        jButton55.setMaximumSize(new java.awt.Dimension(50, 50));
        jButton55.setMinimumSize(new java.awt.Dimension(50, 50));
        jButton55.setPreferredSize(new java.awt.Dimension(50, 50));
        jPanel3.add(jButton55);

        jButton56.setText("jButton1");
        jButton56.setMaximumSize(new java.awt.Dimension(50, 50));
        jButton56.setMinimumSize(new java.awt.Dimension(50, 50));
        jButton56.setPreferredSize(new java.awt.Dimension(50, 50));
        jPanel3.add(jButton56);

        jButton57.setText("jButton1");
        jButton57.setMaximumSize(new java.awt.Dimension(50, 50));
        jButton57.setMinimumSize(new java.awt.Dimension(50, 50));
        jButton57.setPreferredSize(new java.awt.Dimension(50, 50));
        jPanel3.add(jButton57);

        jButton58.setText("jButton1");
        jButton58.setMaximumSize(new java.awt.Dimension(50, 50));
        jButton58.setMinimumSize(new java.awt.Dimension(50, 50));
        jButton58.setPreferredSize(new java.awt.Dimension(50, 50));
        jPanel3.add(jButton58);

        jButton59.setText("jButton1");
        jButton59.setMaximumSize(new java.awt.Dimension(50, 50));
        jButton59.setMinimumSize(new java.awt.Dimension(50, 50));
        jButton59.setPreferredSize(new java.awt.Dimension(50, 50));
        jPanel3.add(jButton59);

        jButton60.setText("jButton1");
        jButton60.setMaximumSize(new java.awt.Dimension(50, 50));
        jButton60.setMinimumSize(new java.awt.Dimension(50, 50));
        jButton60.setPreferredSize(new java.awt.Dimension(50, 50));
        jPanel3.add(jButton60);

        jButton61.setText("jButton1");
        jButton61.setMaximumSize(new java.awt.Dimension(50, 50));
        jButton61.setMinimumSize(new java.awt.Dimension(50, 50));
        jButton61.setPreferredSize(new java.awt.Dimension(50, 50));
        jPanel3.add(jButton61);

        jButton62.setText("jButton1");
        jButton62.setMaximumSize(new java.awt.Dimension(50, 50));
        jButton62.setMinimumSize(new java.awt.Dimension(50, 50));
        jButton62.setPreferredSize(new java.awt.Dimension(50, 50));
        jPanel3.add(jButton62);

        jButton63.setText("jButton1");
        jButton63.setMaximumSize(new java.awt.Dimension(50, 50));
        jButton63.setMinimumSize(new java.awt.Dimension(50, 50));
        jButton63.setPreferredSize(new java.awt.Dimension(50, 50));
        jPanel3.add(jButton63);

        jButton64.setText("jButton1");
        jButton64.setMaximumSize(new java.awt.Dimension(50, 50));
        jButton64.setMinimumSize(new java.awt.Dimension(50, 50));
        jButton64.setPreferredSize(new java.awt.Dimension(50, 50));
        jPanel3.add(jButton64);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(125, 125, 125)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(128, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed
    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton23;
    private javax.swing.JButton jButton24;
    private javax.swing.JButton jButton25;
    private javax.swing.JButton jButton26;
    private javax.swing.JButton jButton27;
    private javax.swing.JButton jButton28;
    private javax.swing.JButton jButton29;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton30;
    private javax.swing.JButton jButton31;
    private javax.swing.JButton jButton32;
    private javax.swing.JButton jButton33;
    private javax.swing.JButton jButton34;
    private javax.swing.JButton jButton35;
    private javax.swing.JButton jButton36;
    private javax.swing.JButton jButton37;
    private javax.swing.JButton jButton38;
    private javax.swing.JButton jButton39;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton40;
    private javax.swing.JButton jButton41;
    private javax.swing.JButton jButton42;
    private javax.swing.JButton jButton43;
    private javax.swing.JButton jButton44;
    private javax.swing.JButton jButton45;
    private javax.swing.JButton jButton46;
    private javax.swing.JButton jButton47;
    private javax.swing.JButton jButton48;
    private javax.swing.JButton jButton49;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton50;
    private javax.swing.JButton jButton51;
    private javax.swing.JButton jButton52;
    private javax.swing.JButton jButton53;
    private javax.swing.JButton jButton54;
    private javax.swing.JButton jButton55;
    private javax.swing.JButton jButton56;
    private javax.swing.JButton jButton57;
    private javax.swing.JButton jButton58;
    private javax.swing.JButton jButton59;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton60;
    private javax.swing.JButton jButton61;
    private javax.swing.JButton jButton62;
    private javax.swing.JButton jButton63;
    private javax.swing.JButton jButton64;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
